### ISSUE TITLE
Mailchimp integration

### ISSUE THREAD

**Issue by telsgaard** [yeyintkoko/admin-clubs#10]
The site must integrate to mailchimp for adding members to the mail list

**Comment by telsgaard** [comment]
I was thinking that we maybe can implement a logic som that we do not keep information about the newsletter subscription in mongodb, but fetches the information from mailchimp? Something like when the email is added to the user, and the checkbox is marked for subscription is marked, the account is created in mailchimp. But when opening time user to edit, the checkbox status is fetched from mailchimp. So is the user has been unsubscribed from mailchimp, the checkbox is not marked. Also can the the checkbox be "grayed out" when a email address isn't added.

**Comment by telsgaard** [comment]
Or keeps it in mongodb, but then on edit, fetches the subskription status from mailchimp, so er tries to keep it in sync

**Comment by yeyintkoko** [comment]
Let's remove the subscribe field from db and fetch from mailchimp.

**Comment by telsgaard** [comment]
Fine, just remember to remove it from CSV export also
