### ISSUE TITLE
Change to sports

### ISSUE THREAD

**Issue by telsgaard** [yeyintkoko/admin-clubs#26]
In order to support the "sports" in 3 different languages, i suggest we change the way it's handled a little.

We could make a DB table with the sports which can be assigned to clubs, they should be kept in 3 languages. It is only the gif admin which has access to create new sports that is inserted in the DB, which then is available for the club admin to assign to the clubs.

The list of sports (in danish) is

Badminton
Håndbold
Fodbold
Qajaq
Arctic Sport
TaeKwondo
Langrend
Alpin
Snowboard
Futsal
Løb
Orienteringsløb
Ældreidræt
Bordtennis
Tennis
Volleyball
Karate
Floorball
Klatring
Boksning
Gymnastik
Armbrydning
Svømning

**Comment by yeyintkoko** [comment]
Good.
I will do it.
