### ISSUE TITLE
Enhanced logging

### ISSUE THREAD

**Issue by telsgaard** [yeyintkoko/admin-clubs#37]
I am going to add the paper trail plugin in heroku, and would like to have logged all login attempts (failed and successful) and all DB operations, preferable including the username of the admin user creating them

**Comment by yeyintkoko** [comment]
Good

**Comment by telsgaard** [comment]
I have added the papertail plugin. The most important logging is successful and failed login attempts (must include the username). Second priority is database operations including the username of the user making them.

**Comment by yeyintkoko** [comment]
Ok
