### ISSUE TITLE
subscribe_news_letter is written false to in MongoDB on unsubscribe

### ISSUE THREAD

**Issue by telsgaard** [yeyintkoko/admin-clubs#47]
When "Subscribe to newsletter" is unchecked, it is written to MongoDB, but I do not think we use the DB field anymore ? If it is not used in MongoDB anymore, we should remove the write to the DB on the edit where the newsletter subscription is set to false.

When subscribing to newsletters, the field is not changed to true, so I believe it's just some old code which can be removed.

**Comment by yeyintkoko** [comment]
Yes, it is an old code. I will remove it.
